### ISSUE TITLE
Error: failed to load modules: module "farallon" not found in "/opt/buildhome/repo/themes/farallon"; either add it as a Hugo Module or store it in "/opt/buildhome/repo/themes".: module does not exist

### ISSUE THREAD

**Issue by hidezember** [bigfa/bigfa.github.io#1]
按照教程配置，在本地可以hugo生成网站
push到github仓库再用cloudflare部署就提示：

16:05:38.783 | Error: failed to load modules: module "farallon" not found in "/opt/buildhome/repo/themes/farallon"; either add it as a Hugo Module or store it in "/opt/buildhome/repo/themes".: module does not exist
-- | --
16:05:38.790 | Failed: Error while executing user command. Exited with error code: 1
16:05:38.798 | Failed: build command exited with code: 1
16:05:39.726 | Failed: error occurred while running build command

找了配置文件都找不到这个module "farallon"在哪

**Comment by bigfa** [comment]
我不知道你是怎么部署的，我建议你用这个Github 的action https://github.com/cloudflare/pages-action。

另外就是其实wp 没任何问题，挺好的，没必要折腾hugo 😂，hugo 评论还得分开管理。

**Comment by hidezember** [comment]
我找到原因了，直接用这段命令：
`git clone https://github.com/bigfa/bigfa.github.io.git
cd bigfa.github.io
git submodule update --init --recursive
hugo serve -D`
虽然本地可以部署起来，但是themes\farallon文件夹是空的，clone一个放里面就好了

看到hugo虽然部署完了，但是还要搞一堆个性化定制，头又大了。
wp应该是ok的……目前的问题是用typora写的文章（特别是多图片的情况），怎么无痛压缩并发布到wp

**Comment by bigfa** [comment]
建议在typora 直接上传图片，有不少直接用s3 api上传的脚本，写完再把内容粘贴到wp好了。
